### ISSUE TITLE
missing API Endpoint on approve Request

### ISSUE THREAD

**Issue by BertramBo** [OneIdentity/IdentityManager.Imx#218]
Hello,

since Commit
https://github.com/OneIdentity/IdentityManager.Imx/pull/202/files#diff-2b596a45c693c6e7ff31411b1dce2e5fdc6777ecc10eefb372b1804f32f77a81
from 19 November there is a change in
imxweb/projects/qer/src/lib/itshopapprove/workflow-action/workflow-single-action/workflow-single-action.component.ts
with a new Call
Line: const entityWrapper = await this.approvalService.getExtendedEntity(this.request.key);

this makes a new GET to the API Service like this:
https://{Servername}/portal/itshop/approve/requests/interactive/{UID...}

we have QER.CompositionApi.Server.PlugIn.dll with Version : 9.2.401.4123 and this do not have this requests/interactive endpoint.

is there an new Version of the DLL available or is there another issue?

Unfortunately, support (Case: #02628444) forwarded me to create a GitHub issue :-(

Best Regards 
Bertram

**Comment by BertramBo** [comment]
Errormessage:
![image](https://github.com/user-attachments/assets/3cd92aaf-5403-4f96-b77f-6bc6c71df393)

**Comment by hannobunjes** [comment]
Hi @BertramBo,

The code fix for the issue 460757 requires a server-side fix to be installed - this fix adds the `interactive` API for request parameters.
I will follow up on your service request internally so that you receive the code fix.

Thanks,
Hanno

**Comment by sebastian-kuebbeler** [comment]
Hello @hannoquest,

Could you please ask Support to create a Knowledge Base article to make the fix available for the wider audience?

Cheers,
     Sebastian

**Comment by BertramBo** [comment]
the Security Hotfix #472612 solve also this issue

**Comment by hannobunjes** [comment]
@BertramBo Thank you for confirming.

**Comment by cservin** [comment]
Hello @hannoquest ,

We noticed that v93 version of source code is still have the call in approval.service.ts to call the
https://{Servername}/portal/itshop/approve/requests/interactive/{UID...} API, but in 9.3 version we don't have the API. 

Could you please advice, do we need to request hotfix for the API (for QER.CompositionApi.Server.PlugIn.dll) or is it possible that you have fix for this in Web source code?

**Comment by hannobunjes** [comment]
Hello @cservin ,
Please request the hotfix through support, as we are unable to provide fixes for server-side issues here.
Thanks.

**Comment by BertramBo** [comment]
Hi @cservin , 

fyi in my QER.CompositionApi.Server.PlugIn.dll Version 9.3.435.1314 i have the API visible

![Image](https://github.com/user-attachments/assets/cc050145-c35e-486a-b0b9-896b3c4c68fa)

maybe #472612 helps

**Comment by cservin** [comment]
Hi @BertramBo,

Thank you for confirming, I have 9.3.418.1316 version, which doesn't have unfortunatelly. That was shipped in official installation of 9.3 version. So I will ask hotfix from support in this case.
